import './globals.css';
import type { ReactNode } from 'react';
import { DarkModeProvider } from './DarkModeProvider';
import { AuthProvider } from '@/lib/auth-context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <DarkModeProvider>
            {children}
          </DarkModeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
